version: "3.3"

services:
    shaneduffy-api-service:
        image: shaneduffy.api.prod.image
        container_name: shaneduffy.api.prod.container
        build:
            context: api
            dockerfile: .docker/prod.dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
        ports:
            - 5000:80
        restart: always
    shaneduffy-angular-service:
        image: shaneduffy.angular.prod.image
        container_name: shaneduffy.angular.prod.container
        build:
            context: site
            dockerfile: .docker/prod.dockerfile
        environment:
            NODE_ENV: production 
        volumes:
            - /app/node_modules/
        ports:
            - 4000:4000
        restart: always
    mongodb:
        image: mongo:5.0.8
        container_name: shaneduffy.mongodb
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
            MONGO_INITDB_DATABASE: admin
        ports:
            - 27017:27017
        volumes:
            - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
            - ~/Databases/shaneduffy-database:/data/db
        