version: "3.3"

services:
    shaneduffy-angular-service:
        image: shaneduffy.angular.prod.image
        container_name: shaneduffy.angular.prod.container
        build:
            context: .
            dockerfile: .docker/prod.dockerfile
        environment:
            NODE_ENV: production 
        volumes:
            - /app/node_modules/
        ports:
            - 4000:4000