version: "3.3"

services:
    shaneduffy-angular-service:
        image: shaneduffy.angular.dev.image
        container_name: shaneduffy.angular.dev.container
        build:
            context: .
            dockerfile: .docker/dev.dockerfile
        environment:
            NODE_ENV: development
        volumes:
            - /app/node_modules/
        ports:
            - 4200:80