version: "3.8"

services:
    shaneduffy-angular-service:
        image: shaneduffy.angular.dev.image
        container_name: shaneduffy.angular.dev.container
        build:
            context: .
            dockerfile: .docker/dev.dockerfile
        environment:
            NODE_ENV: development
        volumes:
            - "./:/usr/share/app"
            - /app/node_modules/
        ports:
            - 4200:80
        command: ["npm", "run", "dev:ssr", "--", "--port", "80"]