version: "3.3"

services:
    shaneduffy-api-service:
        image: shaneduffy.api.prod.image
        container_name: shaneduffy.api.prod.container
        build:
            context: .
            dockerfile: .docker/prod.dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
        ports:
            - 5000:80
    mongodb:
        image: mongo:5.0.8
        container_name: mongodb
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
            MONGO_INITDB_DATABASE: admin
        ports:
            - 27017:27017
        volumes:
            - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
            - ~/Databases/shaneduffy-database:/data/db